# Generated by Django 5.2.2 on 2025-12-07 12:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Decorator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200)),
                ('education', models.CharField(max_length=200)),
                ('graduated_from', models.CharField(max_length=200)),
                ('category', models.IntegerField(choices=[(0, 'Highest'), (1, 'First'), (2, 'No Category')], default=2)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Enterprise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('legal_address', models.CharField(max_length=200)),
                ('ogrn', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='LifeForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Plant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('initial_age', models.IntegerField()),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=200)),
                ('last_name', models.CharField(max_length=200)),
                ('middle_name', models.CharField(blank=True, max_length=200, null=True)),
                ('phone_number', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
            ],
            options={
                'ordering': ['last_name', 'first_name'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Object',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=200)),
                ('is_serviced', models.BooleanField(default=False)),
                ('decorators', models.ManyToManyField(blank=True, null=True, related_name='objects', to='parks_app.decorator')),
            ],
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contract_number', models.CharField(max_length=200)),
                ('contract_date', models.DateField()),
                ('description', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='parks_app.enterprise')),
                ('Object', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='parks_app.object')),
            ],
        ),
        migrations.CreateModel(
            name='ObjectZone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(max_length=200)),
                ('object_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zones', to='parks_app.object')),
            ],
        ),
        migrations.CreateModel(
            name='PlantPlacement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unique_number', models.IntegerField()),
                ('planted_date', models.DateField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='parks_app.plant')),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='placements', to='parks_app.objectzone')),
            ],
        ),
        migrations.CreateModel(
            name='PlantWateringSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency', models.CharField(max_length=200)),
                ('time_watering_start', models.DateField()),
                ('time_watering_end', models.DateField()),
                ('water_norm_liters_winter', models.IntegerField()),
                ('water_norm_liters_summer', models.IntegerField()),
                ('water_norm_liters_fall', models.IntegerField()),
                ('water_norm_liters_spring', models.IntegerField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='schedule', to='parks_app.plant')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('enterprise', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='parks_app.enterprise')),
            ],
        ),
        migrations.CreateModel(
            name='Species',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('possible_planting_period_from', models.DateField()),
                ('possible_planting_period_to', models.DateField()),
                ('flowering_period_from', models.DateField()),
                ('flowering_period_to', models.DateField()),
                ('special_characteristics', models.TextField()),
                ('life_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='species', to='parks_app.lifeform')),
            ],
        ),
        migrations.AddField(
            model_name='plant',
            name='species',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plant', to='parks_app.species'),
        ),
        migrations.CreateModel(
            name='PlantWorkerAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('plant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='parks_app.plant')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='worker_assignments', to='parks_app.worker')),
            ],
        ),
    ]
