# Generated by Django 5.2.2 on 2025-12-07 12:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('parks_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contract',
            old_name='Object',
            new_name='object',
        ),
    ]
