# Generated by Django 5.2.2 on 2025-12-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks_app', '0002_rename_object_contract_object'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='decorators',
            field=models.ManyToManyField(blank=True, related_name='objects', to='parks_app.decorator'),
        ),
    ]
