# Generated by Django 5.2.2 on 2025-12-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks_app', '0003_alter_object_decorators'),
    ]

    operations = [
        migrations.AlterField(
            model_name='species',
            name='flowering_period_from',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='flowering_period_to',
            field=models.TimeField(),
        ),
    ]
