# Generated by Django 5.2.2 on 2025-12-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks_app', '0004_alter_species_flowering_period_from_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plantwateringschedule',
            name='time_watering_end',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='plantwateringschedule',
            name='time_watering_start',
            field=models.TimeField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='flowering_period_from',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='species',
            name='flowering_period_to',
            field=models.DateField(),
        ),
    ]
