# Generated by Django 5.2.2 on 2025-12-07 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parks_app', '0005_alter_plantwateringschedule_time_watering_end_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='object',
            name='decorators',
            field=models.ManyToManyField(blank=True, related_name='serviced_objects', to='parks_app.decorator'),
        ),
    ]
