# Generated by Django 4.2.16 on 2025-12-07 19:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("parks_app", "0006_alter_object_decorators"),
    ]

    operations = [
        migrations.AlterField(
            model_name="contract",
            name="enterprise",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contracts",
                to="parks_app.enterprise",
            ),
        ),
        migrations.AlterField(
            model_name="contract",
            name="object",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="contract_objects",
                to="parks_app.object",
            ),
        ),
    ]
