# Generated by Django 5.2.2 on 2025-12-03 17:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warriors_app', '0002_alter_warrior_skill'),
    ]

    operations = [
        migrations.AlterField(
            model_name='skillofwarrior',
            name='warrior',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills_info', to='warriors_app.warrior', verbose_name='Воин'),
        ),
    ]
